In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("../data/nepal_earthquakes_1990_2026.csv")

Duplicate row

In [4]:
duplicate=df.duplicated().sum()
print("duplicate rows:",duplicate)

duplicate rows: 0

In [5]:
print(df.isnull().sum())

time                 0
latitude             0
longitude            0
depth                0
mag                  0
magType              0
nst                811
gap                369
dmin               803
rms                  4
net                  0
id                   0
updated              0
place                0
type                 0
horizontalError    819
depthError         582
magError           810
magNst              76
status               0
locationSource       0
magSource            0
dtype: int64

Missing value treatment

In [6]:
num_cols=df.select_dtypes(include=np.number).columns
for col in num_cols:
    df[col]=df[col].fillna(df[col].median())

In [7]:
print(df.isnull().sum())

time               0
latitude           0
longitude          0
depth              0
mag                0
magType            0
nst                0
gap                0
dmin               0
rms                0
net                0
id                 0
updated            0
place              0
type               0
horizontalError    0
depthError         0
magError           0
magNst             0
status             0
locationSource     0
magSource          0
dtype: int64

In [8]:
df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-12-07T02:43:07.342Z,29.8698,80.9384,43.404,4.4,mb,21.0,166.0,8.856,0.94,...,2025-12-26T01:20:25.040Z,"37 km E of Dārchulā, Nepal",earthquake,13.18,9.350,0.144,14.0,reviewed,us,us
1,2025-12-04T11:59:01.015Z,29.1109,87.0043,10.000,4.1,mb,36.0,168.0,3.646,1.26,...,2025-12-27T14:38:45.040Z,"130 km N of Lobuche, Nepal",earthquake,10.55,1.930,0.103,26.0,reviewed,us,us
2,2025-11-10T22:44:15.027Z,29.1757,86.8367,10.000,4.2,mb,14.0,164.0,3.779,0.57,...,2025-12-01T01:43:29.040Z,"136 km N of Lobuche, Nepal",earthquake,12.27,1.963,0.199,7.0,reviewed,us,us
3,2025-11-03T20:57:22.312Z,28.5267,87.3673,10.000,4.7,mb,64.0,79.0,3.493,0.77,...,2025-11-23T19:51:34.188Z,"84 km NE of Lobuche, Nepal",earthquake,9.64,1.872,0.058,89.0,reviewed,us,us
4,2025-10-21T14:59:40.611Z,29.0245,85.3683,10.000,4.1,mb,25.0,163.0,5.072,0.44,...,2025-11-13T19:11:33.040Z,"35 km SSE of Saga, China",earthquake,9.46,1.840,0.103,26.0,reviewed,us,us

In [9]:
df.columns

Index(['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst',
       'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'status',
       'locationSource', 'magSource'],
      dtype='object')

rename column name (short form in long form)

In [10]:
df=df.rename(columns={'time':'DateTime','mag':'magnitude','magType':'magnitudeType'})

In [11]:
df.columns

Index(['DateTime', 'latitude', 'longitude', 'depth', 'magnitude',
       'magnitudeType', 'nst', 'gap', 'dmin', 'rms', 'net', 'id', 'updated',
       'place', 'type', 'horizontalError', 'depthError', 'magError', 'magNst',
       'status', 'locationSource', 'magSource'],
      dtype='object')

In [12]:
df=df.drop(columns=['id','updated','net','status','locationSource','magSource'])

In [13]:
df.columns

Index(['DateTime', 'latitude', 'longitude', 'depth', 'magnitude',
       'magnitudeType', 'nst', 'gap', 'dmin', 'rms', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst'],
      dtype='object')

In [14]:
df.tail()

,DateTime,latitude,longitude,depth,magnitude,magnitudeType,nst,gap,dmin,rms,place,type,horizontalError,depthError,magError,magNst
1531,1990-02-21T07:21:17.300Z,28.082,82.430,33.0,4.8,mb,28.0,110.0,1.995,1.2,"14 km ESE of Tuls?pur, Nepal",earthquake,7.7,1.9,0.095,7.0
1532,1990-02-09T15:51:23.020Z,29.925,80.730,33.0,4.6,mb,28.0,110.0,1.995,1.0,"20 km ENE of D?rchul?, Nepal",earthquake,7.7,1.9,0.095,15.0
1533,1990-01-30T15:06:26.080Z,28.599,85.714,52.4,4.5,mb,28.0,110.0,1.995,1.5,"74 km NNW of Kod?ri??, Nepal",earthquake,7.7,17.7,0.095,3.0
1534,1990-01-10T23:01:21.960Z,26.559,86.663,68.5,4.7,mb,28.0,110.0,1.995,1.4,"8 km WNW of R?jbir?j, Nepal",earthquake,7.7,11.6,0.095,4.0
1535,1990-01-09T02:29:26.690Z,28.225,88.163,79.1,5.5,mb,28.0,110.0,1.995,1.0,"86 km NNW of Mangan, India",earthquake,7.7,1.9,0.095,53.0

In [15]:
print(df['place'].unique())

['37 km E of Dārchulā, Nepal' '130 km N of Lobuche, Nepal'
 '136 km N of Lobuche, Nepal' ... '74 km NNW of Kod?ri??, Nepal'
 '8 km WNW of R?jbir?j, Nepal' '86 km NNW of Mangan, India']

In [16]:
problem_places = df[df['place'].str.contains(r'\?')]

print(problem_places['place'].unique())

['48 km WNW of B?glung, Nepal' '58 km WNW of B?glung, Nepal'
 '26 km WNW of Dh?rchula, India' '16 km SSE of Kod?ri??, Nepal'
 '10 km SE of Kod?ri??, Nepal' '37 km SE of D?rchul?, Nepal'
 '43 km NE of Kod?ri??, Nepal' '16 km NW of Dh?rchula, India'
 '21 km NW of Dh?rchula, India' '18 km WNW of Dh?rchula, India'
 '16 km WSW of Kod?ri??, Nepal' '33 km SSE of Kod?ri??, Nepal'
 '15 km E of Odl?b?ri, India' '92 km NE of Kh??db?ri??, Nepal'
 '25 km NW of Kh??db?ri??, Nepal' '68 km NE of Kh??db?ri??, Nepal'
 '14 km SSW of Kod?ri??, Nepal' '40 km NNW of Il?m, Nepal'
 '29 km SSE of Kod?ri??, Nepal' '5 km S of B?glung, Nepal'
 '24 km W of Kod?ri??, Nepal' '22 km SW of Kod?ri??, Nepal'
 '32 km NW of Dh?rchula, India' '24 km SE of D?rchul?, Nepal'
 '31 km NW of B?glung, Nepal' '14 km NE of D?rchul?, Nepal'
 '29 km NNW of Il?m, Nepal' '17 km E of Dhankut?, Nepal'
 '28 km SE of Kod?ri??, Nepal' '44 km SSE of Kod?ri??, Nepal'
 '18 km NE of Dh?rchula, India' '43 km N of Kod?ri??, Nepal'
 '33 km NW of Kod?ri??, Nepal' '40 km SSE of Kod?ri??, Nepal'
 '4 km SSW of P?tan, Nepal' '110 km NNE of Kod?ri??, Nepal'
 '32 km S of Kod?ri??, Nepal' '30 km SE of Kod?ri??, Nepal'
 '36 km SSE of Kod?ri??, Nepal' '24 km SW of Kod?ri??, Nepal'
 '47 km SSE of Kod?ri??, Nepal' '18 km SE of Kod?ri??, Nepal'
 '18 km ESE of Kod?ri??, Nepal' '28 km S of Kod?ri??, Nepal'
 '45 km SSE of Kod?ri??, Nepal' '2 km SE of P?tan, Nepal'
 '60 km NNW of Dh?rchula, India' '68 km NNW of Kod?ri??, Nepal'
 '28 km SSE of Kod?ri??, Nepal' '26 km W of Kod?ri??, Nepal'
 '32 km W of Kod?ri??, Nepal' '12 km NE of Kod?ri??, Nepal'
 '18 km SSE of Kod?ri??, Nepal' '35 km NNW of Kod?ri??, Nepal'
 '31 km NW of Kod?ri??, Nepal' '38 km SSE of Kod?ri??, Nepal'
 '22 km SSE of Kod?ri??, Nepal' '17 km WSW of Kod?ri??, Nepal'
 '14 km ENE of Kod?ri??, Nepal' '38 km ENE of R?mnagar, India'
 '22 km SSW of Kod?ri??, Nepal' '31 km S of Kod?ri??, Nepal'
 '37 km SSE of Kod?ri??, Nepal' '19 km SSE of Kod?ri??, Nepal'
 '35 km SE of Kod?ri??, Nepal' '39 km SSE of Kod?ri??, Nepal'
 '42 km SE of Kod?ri??, Nepal' '28 km E of Kod?ri??, Nepal'
 '34 km SSE of Kod?ri??, Nepal' '39 km SE of Kod?ri??, Nepal'
 '53 km SSE of Kod?ri??, Nepal' '27 km S of Kod?ri??, Nepal'
 '46 km SE of Kod?ri??, Nepal' '25 km SSW of Kod?ri??, Nepal'
 '24 km SSW of Kod?ri??, Nepal' '9 km S of Kod?ri??, Nepal'
 '38 km S of Kod?ri??, Nepal' '30 km S of Kod?ri??, Nepal'
 '35 km SSE of Kod?ri??, Nepal' '15 km S of Kod?ri??, Nepal'
 '34 km SE of Kod?ri??, Nepal' '41 km SE of Kod?ri??, Nepal'
 '22 km S of Kod?ri??, Nepal' '43 km SE of Kod?ri??, Nepal'
 '27 km SSE of Kod?ri??, Nepal' '31 km SE of Kod?ri??, Nepal'
 '37 km E of Kod?ri??, Nepal' '24 km SSE of Kod?ri??, Nepal'
 '37 km SE of Kod?ri??, Nepal' '25 km NNE of Kod?ri??, Nepal'
 '25 km SSE of Kod?ri??, Nepal' '45 km S of Kod?ri??, Nepal'
 '44 km SE of Kod?ri??, Nepal' '42 km SSE of Kod?ri??, Nepal'
 '50 km SSE of Kod?ri??, Nepal' '69 km NNW of Lah?n, Nepal'
 '3 km SSW of Kod?ri??, Nepal' '13 km WNW of Kod?ri??, Nepal'
 '20 km SSE of Kod?ri??, Nepal' '10 km S of Kod?ri??, Nepal'
 '35 km S of Kod?ri??, Nepal' '29 km S of Kod?ri??, Nepal'
 '26 km S of Kod?ri??, Nepal' '16 km SSW of Kod?ri??, Nepal'
 '21 km E of Kod?ri??, Nepal' '36 km S of Kod?ri??, Nepal'
 '26 km SSW of Kod?ri??, Nepal' '33 km S of Kod?ri??, Nepal'
 '21 km SSW of Kod?ri??, Nepal' '68 km NNE of Kod?ri??, Nepal'
 '31 km NNW of Kod?ri??, Nepal' '7 km W of Kod?ri??, Nepal'
 '21 km SW of Kod?ri??, Nepal' '18 km SSW of Kod?ri??, Nepal'
 '13 km ESE of Il?m, Nepal' '22 km SE of Kod?ri??, Nepal'
 '19 km WSW of Kod?ri??, Nepal' '17 km SSW of Kod?ri??, Nepal'
 '15 km WSW of Kod?ri??, Nepal' '27 km SSW of Kod?ri??, Nepal'
 '12 km WNW of Kod?ri??, Nepal' '21 km SSE of Kod?ri??, Nepal'
 '41 km SSE of Kod?ri??, Nepal' '5 km SE of P?tan, Nepal'
 '31 km NNE of Kod?ri??, Nepal' '33 km NNW of Kod?ri??, Nepal'
 '28 km SSW of Kod?ri??, Nepal' '23 km SW of Kod?ri??, Nepal'
 '54 km SSE of Kod?ri??, Nepal' '11 km SSW of Kod?ri??, Nepal'
 '0 km WNW of Panauti??, Nepal' '19 km SW of Kod?ri??, Nepal'
 '13 km SW of Kod?ri??, Nepal' '19 km SSW of Kod?ri??, Nepal'
 '22 km WSW of Kod?ri??, Nepal' '1 km W of Panauti??, Nepal'
 '31 km SSE of Kod?ri??, Nepal' '89 km NNE of Kod?ri??, Nepal'
 '55 km NNW of Dh?rchula, India' '55 km NE of Kh??db?ri??, Nepal'
 '24 km WNW of Kod?ri??, Nepal' '23 km NNW of Kod?ri??, Nepal'
 '58 km NNE of Kod?ri??, Nepal' '13 km NE of D?rchul?, Nepal'
 '61 km NNW of Lah?n, Nepal' '53 km N of Dh?rchula, India'
 '66 km NNW of Kod?ri??, Nepal' '64 km NNW of Kod?ri??, Nepal'
 '11 km W of Dh?rchula, India' '13 km W of Dh?rchula, India'
 '9 km WNW of Dh?rchula, India' '37 km NE of B?geshwar, India'
 '36 km NE of B?geshwar, India' '9 km S of D?rchul?, Nepal'
 '50 km NNW of Dh?rchula, India' '35 km NE of B?geshwar, India'
 '40 km WNW of Dh?rchula, India' '69 km NNE of Kod?ri??, Nepal'
 '58 km NNW of Kod?ri??, Nepal' '25 km WNW of B?glung, Nepal'
 '9 km ESE of B?glung, Nepal' '51 km NNW of Il?m, Nepal'
 '8 km N of Naya B?z?r, India' '72 km NE of Kh??db?ri??, Nepal'
 '10 km E of D?rchul?, Nepal' '25 km E of B?geshwar, India'
 '2 km ENE of Dh?rchula, India' '19 km SW of Dh?rchula, India'
 '8 km SSW of D?rchul?, Nepal' '32 km E of B?geshwar, India'
 '15 km NE of Dadeldhur?, Nepal' '19 km WNW of Kod?ri??, Nepal'
 '60 km ESE of Josh?math, India' '18 km E of B?glung, Nepal'
 '17 km SE of B?glung, Nepal' '46 km N of Dh?rchula, India'
 '58 km N of Lah?n, Nepal' '49 km N of Dh?rchula, India'
 '45 km NW of Dh?rchula, India' '69 km N of Kod?ri??, Nepal'
 '40 km NE of Kod?ri??, Nepal' '35 km NE of Kh??db?ri??, Nepal'
 '15 km NNE of Dh?rchula, India' '32 km WNW of Naya B?z?r, India'
 '17 km SSE of Kod?ri??, Nepal' '83 km NE of Kh??db?ri??, Nepal'
 '14 km SSE of Pithor?garh, India' '16 km W of Kod?ri??, Nepal'
 '50 km ESE of D?rchul?, Nepal' '57 km N of Dh?rchula, India'
 '24 km S of Kod?ri??, Nepal' '19 km ESE of B?glung, Nepal'
 '17 km E of B?glung, Nepal' '22 km ESE of Dhankut?, Nepal'
 '30 km NE of B?geshwar, India' '16 km SSW of B?glung, Nepal'
 '7 km WNW of Naya B?z?r, India' '31 km E of Dhar?n, Nepal'
 '9 km SW of D?rchul?, Nepal' '38 km NE of Kh??db?ri??, Nepal'
 '24 km SE of Kod?ri??, Nepal' '76 km NNE of Kod?ri??, Nepal'
 '17 km SSE of ?ik?pur, Nepal' '46 km WNW of B?glung, Nepal'
 '75 km NE of Kh??db?ri??, Nepal' '51 km SSE of Kod?ri??, Nepal'
 '87 km NE of Kh??db?ri??, Nepal' '23 km E of Dhankut?, Nepal'
 '74 km NW of Kod?ri??, Nepal' '11 km NNW of Kh??db?ri??, Nepal'
 '67 km NE of Kh??db?ri??, Nepal' '30 km NNE of Kh??db?ri??, Nepal'
 '21 km NW of Dadeldhur?, Nepal' '1 km E of Dh?rchula, India'
 '3 km W of D?rjiling, India' '29 km N of Dadeldhur?, Nepal'
 '26 km SSW of D?rchul?, Nepal' '103 km NNE of Kod?ri??, Nepal'
 '34 km NW of B?glung, Nepal' '57 km NE of Kh??db?ri??, Nepal'
 '26 km NNE of Dadeldhur?, Nepal' '76 km E of Josh?math, India'
 '13 km SE of Kh??db?ri??, Nepal' '22 km S of D?rchul?, Nepal'
 '14 km W of Kh??db?ri??, Nepal' '21 km ESE of Lohagh?t, India'
 '24 km ESE of Lohagh?t, India' '38 km W of B?glung, Nepal'
 '14 km ESE of Tuls?pur, Nepal' '20 km ENE of D?rchul?, Nepal'
 '74 km NNW of Kod?ri??, Nepal' '8 km WNW of R?jbir?j, Nepal']

In [17]:
place_corrections = {
    "B?glung": "Baglung",
    "Dh?rchula": "Dharchula",
    "D?rchul?": "Darchula",
    "Kod?ri??": "Kodari",
    "Kh??db?ri??": "Khandbari",
    "Il?m": "Ilam",
    "Dhankut?": "Dhankuta",
    "P?tan": "Patan",
    "Panauti??": "Panauti",
    "R?mnagar": "Ramnagar",
    "B?geshwar": "Bageshwar",
    "Naya B?z?r": "Naya Bazar",
    "Dadeldhur?": "Dadeldhura",
    "Josh?math": "Joshimath",
    "Dhar?n": "Dharan",
    "?ik?pur": "Tikapur",
    "D?rjiling": "Darjiling",
    "Kh??db?ri": "Khandbari",
    "R?jbir?j": "Rajbiraj",
    "Lohagh?t": "Lohaghat",
    "Tuls?pur": "Tulsipur",
    "Pithor?garh": "Pithoragarh",
    "Lah?n":"Lahan",
"Odl?b?ri":"Odlabari"
}

In [18]:
for wrong, correct in place_corrections.items():
    df['place'] = df['place'].str.replace(
        wrong,
        correct,
        regex=False
    )

In [19]:
df.tail()

,DateTime,latitude,longitude,depth,magnitude,magnitudeType,nst,gap,dmin,rms,place,type,horizontalError,depthError,magError,magNst
1531,1990-02-21T07:21:17.300Z,28.082,82.430,33.0,4.8,mb,28.0,110.0,1.995,1.2,"14 km ESE of Tulsipur, Nepal",earthquake,7.7,1.9,0.095,7.0
1532,1990-02-09T15:51:23.020Z,29.925,80.730,33.0,4.6,mb,28.0,110.0,1.995,1.0,"20 km ENE of Darchula, Nepal",earthquake,7.7,1.9,0.095,15.0
1533,1990-01-30T15:06:26.080Z,28.599,85.714,52.4,4.5,mb,28.0,110.0,1.995,1.5,"74 km NNW of Kodari, Nepal",earthquake,7.7,17.7,0.095,3.0
1534,1990-01-10T23:01:21.960Z,26.559,86.663,68.5,4.7,mb,28.0,110.0,1.995,1.4,"8 km WNW of Rajbiraj, Nepal",earthquake,7.7,11.6,0.095,4.0
1535,1990-01-09T02:29:26.690Z,28.225,88.163,79.1,5.5,mb,28.0,110.0,1.995,1.0,"86 km NNW of Mangan, India",earthquake,7.7,1.9,0.095,53.0

In [23]:
df.to_csv("../data/cleaned_data.csv",index=False)
print("csv file saved successfully !!")

csv file saved successfully !!