In [60]:
import numpy as np
import pandas as pd

In [61]:
data=pd.read_csv("../data/cleaned_data.csv")
data.head()

,DateTime,latitude,longitude,depth,magnitude,magnitudeType,nst,gap,dmin,rms,place,type,horizontalError,depthError,magError,magNst
0,2025-12-07T02:43:07.342Z,29.8698,80.9384,43.404,4.4,mb,21.0,166.0,8.856,0.94,"37 km E of Dārchulā, Nepal",earthquake,13.18,9.350,0.144,14.0
1,2025-12-04T11:59:01.015Z,29.1109,87.0043,10.000,4.1,mb,36.0,168.0,3.646,1.26,"130 km N of Lobuche, Nepal",earthquake,10.55,1.930,0.103,26.0
2,2025-11-10T22:44:15.027Z,29.1757,86.8367,10.000,4.2,mb,14.0,164.0,3.779,0.57,"136 km N of Lobuche, Nepal",earthquake,12.27,1.963,0.199,7.0
3,2025-11-03T20:57:22.312Z,28.5267,87.3673,10.000,4.7,mb,64.0,79.0,3.493,0.77,"84 km NE of Lobuche, Nepal",earthquake,9.64,1.872,0.058,89.0
4,2025-10-21T14:59:40.611Z,29.0245,85.3683,10.000,4.1,mb,25.0,163.0,5.072,0.44,"35 km SSE of Saga, China",earthquake,9.46,1.840,0.103,26.0

convert time column

In [62]:
print(data['DateTime'])

0       2025-12-07T02:43:07.342Z
1       2025-12-04T11:59:01.015Z
2       2025-11-10T22:44:15.027Z
3       2025-11-03T20:57:22.312Z
4       2025-10-21T14:59:40.611Z
                  ...
1531    1990-02-21T07:21:17.300Z
1532    1990-02-09T15:51:23.020Z
1533    1990-01-30T15:06:26.080Z
1534    1990-01-10T23:01:21.960Z
1535    1990-01-09T02:29:26.690Z
Name: DateTime, Length: 1536, dtype: object

In [63]:
data['DateTime']=pd.to_datetime(data['DateTime'])
data['DateTime']

0      2025-12-07 02:43:07.342000+00:00
1      2025-12-04 11:59:01.015000+00:00
2      2025-11-10 22:44:15.027000+00:00
3      2025-11-03 20:57:22.312000+00:00
4      2025-10-21 14:59:40.611000+00:00
                     ...
1531   1990-02-21 07:21:17.300000+00:00
1532   1990-02-09 15:51:23.020000+00:00
1533   1990-01-30 15:06:26.080000+00:00
1534   1990-01-10 23:01:21.960000+00:00
1535   1990-01-09 02:29:26.690000+00:00
Name: DateTime, Length: 1536, dtype: datetime64[ns, UTC]

extract year

In [64]:
data['year']=data['DateTime'].dt.year
data['year']

0       2025
1       2025
2       2025
3       2025
4       2025
        ...
1531    1990
1532    1990
1533    1990
1534    1990
1535    1990
Name: year, Length: 1536, dtype: int32

extract month

In [65]:
data['month']=data['DateTime'].dt.month
data['month']

0       12
1       12
2       11
3       11
4       10
        ..
1531     2
1532     2
1533     1
1534     1
1535     1
Name: month, Length: 1536, dtype: int32

extract day

In [66]:
data['day'] = data['DateTime'].dt.day
data['day']

0        7
1        4
2       10
3        3
4       21
        ..
1531    21
1532     9
1533    30
1534    10
1535     9
Name: day, Length: 1536, dtype: int32

extract hour,weekend

In [67]:
data['hour']=data['DateTime'].dt.hour
data['weekday'] = data['DateTime'].dt.dayofweek

In [68]:
data.head()

,DateTime,latitude,longitude,depth,magnitude,magnitudeType,nst,gap,dmin,rms,...,type,horizontalError,depthError,magError,magNst,year,month,day,hour,weekday
0,2025-12-07 02:43:07.342000+00:00,29.8698,80.9384,43.404,4.4,mb,21.0,166.0,8.856,0.94,...,earthquake,13.18,9.350,0.144,14.0,2025,12,7,2,6
1,2025-12-04 11:59:01.015000+00:00,29.1109,87.0043,10.000,4.1,mb,36.0,168.0,3.646,1.26,...,earthquake,10.55,1.930,0.103,26.0,2025,12,4,11,3
2,2025-11-10 22:44:15.027000+00:00,29.1757,86.8367,10.000,4.2,mb,14.0,164.0,3.779,0.57,...,earthquake,12.27,1.963,0.199,7.0,2025,11,10,22,0
3,2025-11-03 20:57:22.312000+00:00,28.5267,87.3673,10.000,4.7,mb,64.0,79.0,3.493,0.77,...,earthquake,9.64,1.872,0.058,89.0,2025,11,3,20,0
4,2025-10-21 14:59:40.611000+00:00,29.0245,85.3683,10.000,4.1,mb,25.0,163.0,5.072,0.44,...,earthquake,9.46,1.840,0.103,26.0,2025,10,21,14,1

keeping useful numerical feature

In [69]:
features = [
    'latitude',
    'magnitude',
    'longitude',
    'depth',
    'nst',
    'gap',
    'dmin',
    'rms',
    'horizontalError',
    'depthError',
    'magError',
    'magNst',
    'year',
    'month',
    'day',
    'hour',
    'weekday'
]

handle categorical columns

In [70]:
data.columns

Index(['DateTime', 'latitude', 'longitude', 'depth', 'magnitude',
       'magnitudeType', 'nst', 'gap', 'dmin', 'rms', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'year', 'month',
       'day', 'hour', 'weekday'],
      dtype='object')

In [71]:
for cols in ['magnitudeType','type','place']:
    
    print(data[cols].value_counts())

magnitudeType
mb     1449
mwc      45
mww      22
ml        8
mwb       5
mw        3
ms        3
mwr       1
Name: count, dtype: int64
type
earthquake    1536
Name: count, dtype: int64
place
Southern Tibetan Plateau        50
Nepal                           17
western Xizang                  10
110 km NW of Rikaze, China       9
119 km NW of Rikaze, China       8
                                ..
14 km SW of Kirtipur, Nepal      1
4 km ENE of Dhulikhel, Nepal     1
16 km SSW of Kodari, Nepal       1
21 km E of Kodari, Nepal         1
86 km NNW of Mangan, India       1
Name: count, Length: 1183, dtype: int64

one hot encoding

In [72]:
data.columns

Index(['DateTime', 'latitude', 'longitude', 'depth', 'magnitude',
       'magnitudeType', 'nst', 'gap', 'dmin', 'rms', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'year', 'month',
       'day', 'hour', 'weekday'],
      dtype='object')

In [73]:
cat_cols = [
    'magnitudeType',
    'type',
    'place'
]

data = pd.get_dummies(data, columns=cat_cols, drop_first=True)

In [74]:
data.head()

,DateTime,latitude,longitude,depth,magnitude,nst,gap,dmin,rms,horizontalError,...,"place_99 km NNW of Lobujya, Nepal","place_99 km NW of Rikaze, China","place_99 km WNW of Saga, China",place_Nepal,place_Nepal-India border region,place_Southern Tibetan Plateau,place_Southern Tibetan Plateau,place_Xizang-Nepal border region,place_western Xizang,place_western Xizang-India border region
0,2025-12-07 02:43:07.342000+00:00,29.8698,80.9384,43.404,4.4,21.0,166.0,8.856,0.94,13.18,...,False,False,False,False,False,False,False,False,False,False
1,2025-12-04 11:59:01.015000+00:00,29.1109,87.0043,10.000,4.1,36.0,168.0,3.646,1.26,10.55,...,False,False,False,False,False,False,False,False,False,False
2,2025-11-10 22:44:15.027000+00:00,29.1757,86.8367,10.000,4.2,14.0,164.0,3.779,0.57,12.27,...,False,False,False,False,False,False,False,False,False,False
3,2025-11-03 20:57:22.312000+00:00,28.5267,87.3673,10.000,4.7,64.0,79.0,3.493,0.77,9.64,...,False,False,False,False,False,False,False,False,False,False
4,2025-10-21 14:59:40.611000+00:00,29.0245,85.3683,10.000,4.1,25.0,163.0,5.072,0.44,9.46,...,False,False,False,False,False,False,False,False,False,False

nepal earthquack often cluster geographically ,create resional feature

In [75]:
def region(lat):
    
    if lat < 27.5:
        return "South"
    
    elif lat < 29:
        return "Central"
    
    else:
        return "North"

data['region'] = data['latitude'].apply(region)

In [76]:
data = pd.get_dummies(
    data,
    columns=['region'],
    drop_first=True
)

feature selection

In [77]:
corr = data.corr(numeric_only=True)

corr['magnitude'].sort_values(
    ascending=False
)

magnitude            1.000000
nst                  0.519215
magNst               0.485623
magnitudeType_mww    0.375327
magnitudeType_mwc    0.303917
                       ...
region_North        -0.115887
latitude            -0.137263
rms                 -0.140742
magError            -0.284354
gap                 -0.571929
Name: magnitude, Length: 1208, dtype: float64

In [78]:
y=data['magnitude']